/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.fabricaElGuardian;
import Logica.iControladorVentas;
import Logica.producto;
import Logica.proveedor;
import Logica.utilidades;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author PabloP
 */
public class AltaProducto extends javax.swing.JInternalFrame {
    
    iControladorVentas ICV = fabricaElGuardian.getInstance().getInstanceIControladorVentas();
    String path = "";
    String ruta = ICV.getRutaImgProducto();
    String rutasrv = ICV.getRutaGuardarimgProductosSrv();
    BufferedImage fotoProducto = null;
    utilidades util = utilidades.getInstance();
    List<proveedor> proveedores = null;
    private JDesktopPane escritorio;

    /**
     * Creates new form AltaMascota
     */
    public AltaProducto(JDesktopPane escritorioV) {
        this.escritorio = escritorioV;
        initComponents();
        cargarProveedores();
        controlJDATE();
        //frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //sp.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_nombre = new javax.swing.JTextField();
        jtxt_cantidad = new javax.swing.JTextField();
        jtxt_precio = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxt_descripcion = new javax.swing.JTextArea();
        jCB_proveedores = new javax.swing.JComboBox<>();
        lb_foto = new javax.swing.JLabel();
        btn_foto = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_aceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jdc_fechaCompra = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Cantidad");

        jLabel3.setText("Precio");

        jLabel4.setText("Descripcion");

        jLabel5.setText("Proveedor");

        jtxt_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_cantidadKeyTyped(evt);
            }
        });

        jtxt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_precioActionPerformed(evt);
            }
        });
        jtxt_precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_precioKeyTyped(evt);
            }
        });

        jtxt_descripcion.setColumns(20);
        jtxt_descripcion.setRows(5);
        jScrollPane1.setViewportView(jtxt_descripcion);

        jCB_proveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lb_foto.setText("FOTO");

        btn_foto.setText("Seleccionar Foto");
        btn_foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_fotoActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        jLabel6.setText("Fecha Compra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jtxt_cantidad, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_precio, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB_proveedores, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt_nombre)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jdc_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_foto, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(lb_foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar)
                .addGap(63, 63, 63)
                .addComponent(btn_aceptar)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_foto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCB_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jdc_fechaCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_aceptar))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioActionPerformed

    private void jtxt_precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_precioKeyTyped
        util.numerosYcomas(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_precioKeyTyped

    private void jtxt_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_cantidadKeyTyped
        util.numerosYcomas(evt);        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_cantidadKeyTyped

    private void btn_fotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_fotoActionPerformed
        selecImagen();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_fotoActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        altaProducto();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_foto;
    private javax.swing.JComboBox<String> jCB_proveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdc_fechaCompra;
    private javax.swing.JTextField jtxt_cantidad;
    private javax.swing.JTextArea jtxt_descripcion;
    private javax.swing.JTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_precio;
    private javax.swing.JLabel lb_foto;
    // End of variables declaration//GEN-END:variables

    private void selecImagen() {
        BufferedImage image = util.levantarImagen(jtxt_cantidad);
        lb_foto.setIcon(new ImageIcon(image));
        System.out.println(lb_foto.getWidth() + "//" + lb_foto.getHeight());
        Image scaledInstance = image.getScaledInstance(lb_foto.getWidth(), lb_foto.getHeight(), Image.SCALE_DEFAULT);
        lb_foto.setIcon(new ImageIcon(scaledInstance));
        fotoProducto = image;
        
    }
    
    private String generarNombreFoto() {
        
        String nombre;
        nombre = "PRODUCTO" + jtxt_nombre.getText() + "_" + "PROVEEDOR" + jCB_proveedores.getSelectedItem();
        return nombre;
    }
    
    private void cargarProveedores() {
        this.proveedores = (List<proveedor>) ICV.getProveedores();
        
        JComboBox<String> nuevoCombo = new JComboBox<>();
        
        if (proveedores.size() > 0) {
            nuevoCombo.addItem("Seleccionar Proveedor");
            for (proveedor p : proveedores) {
                String nuevoValor = p.getId() + "--" + "Nombre: " + p.getNombreProveedor();
                nuevoCombo.addItem(nuevoValor);
            }
        } else {
            nuevoCombo.addItem("No hay proveedores");
        }
        jCB_proveedores.setModel(nuevoCombo.getModel());
    }
    
    private boolean validarDatos() {
        if (jtxt_nombre.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre!");
            jtxt_nombre.requestFocus();
            return false;
        }
        if (jtxt_cantidad.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una cantidad!");
            jtxt_cantidad.requestFocus();
            return false;
        }
        if (jtxt_precio.getText().length() <= 0) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un precio!");
            jtxt_precio.requestFocus();
            return false;
        } else {
            if (Float.valueOf(jtxt_precio.getText()) < 0) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un precio valido!");
                return false;
            }
            
        }
        if (jCB_proveedores.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccecionar un proveedor!");
            jCB_proveedores.requestFocus();
            return false;
            
        }
        if (jdc_fechaCompra.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha!");
            jdc_fechaCompra.requestFocus();
            return false;
        }
        return true;
    }
    
    private void altaProducto() {
        if (JOptionPane.showConfirmDialog(this, "Desea dar de alta el Producto: " + jtxt_nombre.getText() + "?") == 0) {
            if (validarDatos()) {
                producto p = new producto();
                p.setNombre(jtxt_nombre.getText());
                p.setPrecio(Float.valueOf(jtxt_precio.getText()));
                p.setCantidad(Integer.parseInt(jtxt_cantidad.getText()));
                p.setProveedor(getProveedorSeleccionado());
                p.setFechaDeCompra(jdc_fechaCompra.getDate());
                p.setEstado(ICV.getEstado(1));
                p.setDisponible(true);
                if (jtxt_descripcion.getText().length() > 0) {
                    p.setDescripcion(jtxt_descripcion.getText());
                }
                if (fotoProducto != null) {
                    util.salvarImagen(fotoProducto, ruta, generarNombreFoto(), 0);
                    util.salvarImagen(fotoProducto, rutasrv, generarNombreFoto(), 0);
                    p.setFoto(generarNombreFoto()+".png");
                } else {
                    p.setFoto("default");
                }
                if (ICV.altaProducto(p)) {
                    JOptionPane.showMessageDialog(this, "Se agrego el producto: " + jtxt_nombre.getText());
                    limpiar();
                    recargarPadre();
                    this.dispose();
                }
                
            }
            
        }
        
    }
    
    private proveedor getProveedorSeleccionado() {
        String selectedItem = (String) jCB_proveedores.getSelectedItem();
        return ICV.getProveedor(getIdProveedor(selectedItem));
    }
    
    private void limpiar() {
        cargarProveedores();
        jtxt_cantidad.setText(null);
        jtxt_descripcion.setText(null);
        jtxt_nombre.setText(null);
        jtxt_precio.setText(null);
        lb_foto.setIcon(null);
        jdc_fechaCompra.setDate(util.getFechaActual());
    }
    
    private void recargarPadre() {
        JInternalFrame[] allFrames = this.escritorio.getAllFrames();
        for (JInternalFrame jif : allFrames) {
            if (jif instanceof ListarProductos) {
                ListarProductos prod = (ListarProductos) jif;
                prod.cargarTablas();
            }
        }
    }
    
    private long getIdProveedor(String selectedItem) {
        String[] split = selectedItem.split("--");
        return Long.valueOf(split[0]);
    }
    
    private void controlJDATE() {
        
        Date max = util.getFechaActual();//fecha minima
        Date min = utilidades.sumaRestaDias(util.getFechaActual(), -30);//fecha maxima 7 dias a partir de la actual
        jdc_fechaCompra.getDateEditor().setEnabled(false);//desabilito el jtext editor
        jdc_fechaCompra.setMaxSelectableDate(max);//seteo ma fecha maxima
         jdc_fechaCompra.setMinSelectableDate(min);//seteo la fecha minima
        //en este evento se le pueden agregar llamadas a opciones mentodos etc que se ejecutan cuando cambia la fecha (uso la interfaz lambda)
        /* JDTFechaReserva.getDateEditor().addPropertyChangeListener((PropertyChangeEvent e) -> {
            JOptionPane.showMessageDialog(rootPane, "la fecha es " + JDTFechaReserva.getDate());
        // btn_turno.setEnabled(false);
        });*/
        
    }
}
