/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ControladorVentas;
import Logica.proveedor;
import Logica.utilidades;
import java.util.List;
import java.util.function.ObjDoubleConsumer;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jp
 */
public class JIF_proveedor extends javax.swing.JInternalFrame {

    private ControladorVentas contV = ControladorVentas.getInstance();
    utilidades util = utilidades.getInstance();
    private Long id = null;
    private List<proveedor> proveedores = null;
    private JDesktopPane escritorio;

    /**
     * Creates new form JIF_proveedor
     */
    public JIF_proveedor(JDesktopPane escritorioV) {

        this.escritorio = escritorioV;
        initComponents();
        cargarProveedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_proveedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        jtxt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_buscarKeyTyped(evt);
            }
        });

        jtabla_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabla_proveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtabla_proveedor);

        jLabel1.setText("Buscar");

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(jtxt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_salir)))
                    .addComponent(btn_modificar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_agregar)
                        .addGap(41, 41, 41)
                        .addComponent(btn_modificar)
                        .addGap(43, 43, 43)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir)
                        .addGap(33, 33, 33))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtabla_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabla_proveedorMouseClicked
        int rowAtPoint = jtabla_proveedor.rowAtPoint(evt.getPoint()); // TODO add your handling code here:
        this.id = (Long) jtabla_proveedor.getValueAt(rowAtPoint, 0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jtabla_proveedorMouseClicked

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea ingresar un nuevo Proveedor?") == 0) {
            JIF_altaProveedor altaProv = new JIF_altaProveedor(this.escritorio);
            escritorio.add(altaProv);
            altaProv.setVisible(true);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        if (id != null) {
            if (JOptionPane.showConfirmDialog(this, "Desea modificar el proveedor: " + id) == 0) {
                JIF_modificarProveedor modProv = new JIF_modificarProveedor(id, escritorio);
                escritorio.add(modProv);
                modProv.setVisible(true);

            } else {
                id = null;
            }
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (id != null) {
            if (JOptionPane.showConfirmDialog(this, "Desea eliminar el proveedor: " + id) == 0) {
                if (contV.eliminarProveedor(id)) {

                    JOptionPane.showMessageDialog(this, "Se elimino el proveedor: " + id);
                    cargarProveedores();
                }

            } else {
                id = null;
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void jtxt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_buscarKeyTyped
        util.filtrarTabla(jtxt_buscar.getText(), jtabla_proveedor);        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_buscarKeyTyped

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtabla_proveedor;
    private javax.swing.JTextField jtxt_buscar;
    // End of variables declaration//GEN-END:variables

/////////////////////funciones
    public void cargarProveedores() {
        this.proveedores = (List<proveedor>) contV.getProveedores();
        if (proveedores.size() > 0) {
            String[] cabeceras = util.cabeceras(proveedores.get(0));
            DefaultTableModel dtm = new DefaultTableModel(cabeceras, 0);
            /*id/=" + id + "/RUT/" + RUT + "/direccion/" + direccion + "/correo/" + correo + "/numeroTelCel/" + numeroTelCel;*/
            for (proveedor p : proveedores) {
                Object[] data = {p.getId(), p.getRUT(), p.getDireccion(), p.getCorreo(), p.getNumeroTelCel()};
                dtm.addRow(data);
            }
            jtabla_proveedor.setModel(dtm);
            jtabla_proveedor.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(this, "No hay proveedores en el sistema!");
            jtabla_proveedor.setEnabled(false);
        }

    }

}
