/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.utilidades;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.internet.AddressException;
import javax.swing.JOptionPane;

/**
 *
 * @author jp
 */
public class JIF_enviarCorreo extends javax.swing.JInternalFrame {

    private String correo = null;
    private String cuerpo = null;
    utilidades util = utilidades.getInstance();

    /**
     * Creates new form JIF_enviarCorreo
     */
    public JIF_enviarCorreo(String cuerpo,String correo) {
        this.correo=correo;
        this.cuerpo=cuerpo;
        initComponents();
        validaInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_remitente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxt_Destinatario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxt_asunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxt_cuerpo = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        btn_cambiarDest = new javax.swing.JButton();

        jLabel1.setText("Correo");

        jLabel2.setText("Destinatario");

        jLabel3.setText("Asunto");

        jLabel4.setText("Mensaje");

        btn_enviar.setText("Enviar");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");

        btn_cambiarDest.setText("Cambiar");
        btn_cambiarDest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiarDestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_enviar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancelar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(58, 58, 58)
                                            .addComponent(jtxt_remitente, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtxt_Destinatario)
                                                .addComponent(jtxt_asunto))))
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_cambiarDest))
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jtxt_cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_remitente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_Destinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cambiarDest))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jtxt_cuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_enviar)
                    .addComponent(btn_cancelar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        enviar();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void btn_cambiarDestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiarDestActionPerformed
        jtxt_Destinatario.setEditable(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cambiarDestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiarDest;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxt_Destinatario;
    private javax.swing.JTextField jtxt_asunto;
    private javax.swing.JTextField jtxt_cuerpo;
    private javax.swing.JTextField jtxt_remitente;
    // End of variables declaration//GEN-END:variables
///////////funciones
    public void recibeCorreo(String correo) {
        this.correo = correo;

    }

    public void recibePedido(String pedido, String correo) {
        this.correo = correo;
        this.cuerpo = pedido;
    }

    private void validaInicio() {
        if (this.correo != null) {
            jtxt_Destinatario.setText(this.correo);
            jtxt_Destinatario.setEditable(false);
        }
        if (this.cuerpo != null) {
            jtxt_cuerpo.setText(this.cuerpo);
            jtxt_asunto.setText("Pedido");

        }
        jtxt_remitente.setText(utilidades.getUsername());
        jtxt_remitente.setEditable(false);
    }

    private void enviar() {
        if (jtxt_Destinatario.getText().length() > 0) {

            if (util.emailValido(jtxt_Destinatario.getText())) {
                try {
                    if (utilidades.enviarConGMail(jtxt_Destinatario.getText(), jtxt_asunto.getText(), jtxt_cuerpo.getText(), null, null)) {
                        JOptionPane.showMessageDialog(this, "Se envio el correo!");

                        limpiar();
                        this.dispose();
                    }
                } catch (AddressException ex) {
                    System.err.println("Error al enviar: " + ex.getMessage() + " CAUSA: " + ex.getCause());
                    JOptionPane.showMessageDialog(this, "Error al enviar!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe ingresar un correo valido!");
                jtxt_Destinatario.requestFocus();
                jtxt_Destinatario.selectAll();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un correo valido!");
            jtxt_Destinatario.requestFocus();
        }
    }

    private void limpiar() {
        jtxt_Destinatario.setText(null);
        jtxt_asunto.setText(null);
        jtxt_cuerpo.setText(null);
        this.correo = null;
        this.cuerpo = null;
    }

}
