/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.ControladorVentas;
import Logica.proveedor;
import Logica.utilidades;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jp
 */
public class JIF_modificarProveedor extends javax.swing.JInternalFrame {
    
    private JDesktopPane escritorio = null;
    private long idProveedor = 0;
    utilidades util = utilidades.getInstance();
    ControladorVentas contV = ControladorVentas.getInstance();
    private proveedor provMod;

    /**
     * Creates new form JIF_modificarProveedor
     */
    public JIF_modificarProveedor(long idProv, JDesktopPane escritorioV) {
        this.idProveedor = idProv;
        this.escritorio = escritorioV;
        initComponents();
        cargarProveedor();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_nombreProveedor = new javax.swing.JTextField();
        jtxt_rut = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_direccion = new javax.swing.JTextField();
        jtxt_correo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_telefono = new javax.swing.JTextField();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("RUT");

        jLabel3.setText("Direccion");

        jtxt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_direccionActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo");

        jLabel5.setText("Tel-Cel");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_aceptar)
                        .addGap(36, 36, 36)
                        .addComponent(btn_cancelar))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(28, 28, 28)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxt_nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxt_direccion)
                                .addComponent(jtxt_correo)
                                .addComponent(jtxt_telefono)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_aceptar)
                    .addComponent(btn_cancelar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_direccionActionPerformed

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Desea modificar el proveedor: " + jtxt_nombreProveedor.getText()) == 0) {
            modificarProveedor();
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtxt_correo;
    private javax.swing.JTextField jtxt_direccion;
    private javax.swing.JTextField jtxt_nombreProveedor;
    private javax.swing.JTextField jtxt_rut;
    private javax.swing.JTextField jtxt_telefono;
    // End of variables declaration//GEN-END:variables

    private void cargarProveedor() {
        this.provMod = (proveedor) contV.getProveedor(this.idProveedor);
        
        jtxt_nombreProveedor.setText(provMod.getNombreProveedor());
        jtxt_rut.setText(provMod.getRUT());
        jtxt_rut.setEditable(false);
        jtxt_correo.setText(provMod.getCorreo());
        jtxt_direccion.setText(provMod.getDireccion());
        jtxt_telefono.setText(provMod.getNumeroTelCel());
    }
    
    private boolean validaDatos() {
        
        if (jtxt_nombreProveedor.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un Nombre para el proveedor!");
            jtxt_nombreProveedor.requestFocus();
            return false;
        }
        if (jtxt_direccion.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una direccion para el proveedor!");
            jtxt_direccion.requestFocus();
            return false;
        }
        if (jtxt_correo.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un correo!");
            jtxt_correo.requestFocus();
            return false;
        }
        if (jtxt_correo.getText() != null) {
            if (!util.emailValido(jtxt_correo.getText())) {
                JOptionPane.showMessageDialog(this, "Debe ingresar un correo valido!");
                jtxt_correo.requestFocus();
                return false;
            }
            
        }
        if (jtxt_telefono.getText() == null) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un telefono");
            jtxt_telefono.requestFocus();
            return false;
        }
        return true;
        
    }
    
    private void modificarProveedor() {
        if (validaDatos()) {
            if (modificar()) {
                if (contV.modificarProveedor(provMod)) {
                    JOptionPane.showMessageDialog(this, "Se modifico el proveedor: " + jtxt_rut.getText());
                    limpiar();
                    recargarPadre();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al dar de modificar el proveedor!");
                }
            }
        }
    }
    
    private boolean modificar() {
        boolean resultado = false;
        if (!provMod.getNombreProveedor().equals(jtxt_nombreProveedor.getText())) {
            provMod.setNombreProveedor(jtxt_nombreProveedor.getText());
            resultado = true;
        }
        if (!provMod.getCorreo().equals(jtxt_correo.getText())) {
            provMod.setCorreo(jtxt_correo.getText());
            
            resultado = true;
        }
        
        if (!provMod.getDireccion().equals(jtxt_direccion.getText())) {
            provMod.setDireccion(jtxt_direccion.getText());
            resultado = true;
        }
        
        if (!provMod.getNumeroTelCel().equals(jtxt_telefono.getText())) {
            provMod.setNumeroTelCel(jtxt_telefono.getText());
            resultado = true;
        }
        return resultado;
    }
    
    private void limpiar() {
        jtxt_correo.setText(null);
        jtxt_direccion.setText(null);
        jtxt_nombreProveedor.setText(null);
        jtxt_rut.setText(null);
        jtxt_telefono.setText(null);
        
    }
    
     private void recargarPadre(){
     JInternalFrame[] allFrames = this.escritorio.getAllFrames();
        for (JInternalFrame jif : allFrames) {
            if (jif instanceof JIF_proveedor) {
                JIF_proveedor jifProv = (JIF_proveedor) jif;
                jifProv.cargarProveedores();
            }
        }
    
    }
}
