/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.GenerarPDF;
import Logica.fabricaElGuardian;
import Logica.iControladorVentas;
import Logica.producto;
import Logica.proveedor;
import Logica.utilidades;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;

import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author PabloP
 */
public class ListarProductos extends javax.swing.JInternalFrame {

    private static iControladorVentas iCV = fabricaElGuardian.getInstance().getInstanceIControladorVentas();
    private static JDesktopPane escritorio = null;
    //ModificarProducto modProd = new ModificarProducto();
    utilidades util = utilidades.getInstance();
    private Long idProdTS = null, idProdTSS = null, idProdTP = null;
    private proveedor prov = null;
    private String correoProv;
    private producto prod = null;
    private Long idproductoRecibido = null;

    /**
     * Creates new form ListarProductos
     */
    public ListarProductos(JDesktopPane escritorioV) {
        this.escritorio = escritorioV;
        initComponents();
        cargarTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablaProdS = new javax.swing.JTable();
        btn_nuevoS = new javax.swing.JButton();
        btn_modidicarS = new javax.swing.JButton();
        btn_eliminarS = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_buscar1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablaProdSS = new javax.swing.JTable();
        btn_pedir = new javax.swing.JButton();
        btn_modificarSS = new javax.swing.JButton();
        btn_eliminarSS = new javax.swing.JButton();
        btn_salir2 = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_buscar2 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtablaProdP = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_codigo = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_precio = new javax.swing.JLabel();
        lb_fecha = new javax.swing.JLabel();
        lb_nomProv = new javax.swing.JLabel();
        lb_rut = new javax.swing.JLabel();
        lb_direcciion = new javax.swing.JLabel();
        lb_correo = new javax.swing.JLabel();
        lb_telCel = new javax.swing.JLabel();
        btn_contacto = new javax.swing.JButton();
        btn_salir3 = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtxt_buscar3 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtabla_productoRP = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtabla_productosRecibidos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jLabel1.setText("Buscar");

        jtxt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_buscarKeyTyped(evt);
            }
        });

        jtablaProdS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaProdS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaProdSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablaProdS);

        btn_nuevoS.setText("Nuevo");
        btn_nuevoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoSActionPerformed(evt);
            }
        });

        btn_modidicarS.setText("Modificar");
        btn_modidicarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modidicarSActionPerformed(evt);
            }
        });

        btn_eliminarS.setText("Eliminar");
        btn_eliminarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarSActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_nuevoS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_modidicarS, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btn_eliminarS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_salir)
                                .addGap(21, 21, 21)))
                        .addGap(42, 42, 42))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_nuevoS, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_modidicarS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_eliminarS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos En Stock", jInternalFrame1);

        jInternalFrame2.setVisible(true);

        jLabel2.setText("Buscar");

        jtxt_buscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_buscar1KeyTyped(evt);
            }
        });

        jtablaProdSS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaProdSS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaProdSSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtablaProdSS);

        btn_pedir.setText("Pedir");
        btn_pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pedirActionPerformed(evt);
            }
        });

        btn_modificarSS.setText("Modificar");
        btn_modificarSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarSSActionPerformed(evt);
            }
        });

        btn_eliminarSS.setText("Eliminar");
        btn_eliminarSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarSSActionPerformed(evt);
            }
        });

        btn_salir2.setText("Salir");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 977, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_pedir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_modificarSS, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btn_eliminarSS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_salir2)
                                .addGap(21, 21, 21)))
                        .addGap(42, 42, 42))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxt_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_pedir, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btn_modificarSS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btn_eliminarSS, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir2)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos Sin Stock", jInternalFrame2);

        jInternalFrame3.setVisible(true);

        jLabel3.setText("Buscar");

        jtxt_buscar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_buscar2KeyTyped(evt);
            }
        });

        jtablaProdP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablaProdP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaProdPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtablaProdP);

        jLabel4.setText("Codigo");

        jLabel5.setText("Nombre");

        jLabel6.setText("Precio");

        jLabel7.setText("Fecha de compra");

        jLabel8.setText("Nombre Proveedor");

        jLabel9.setText("RUT");

        jLabel10.setText("Direccion");

        jLabel11.setText("Correo");

        jLabel12.setText("Tel/Cel");

        lb_codigo.setText("Codigo");

        lb_nombre.setText("Nombre");

        lb_precio.setText("Precio");

        lb_fecha.setText("Fecha");

        lb_nomProv.setText("Nombre");

        lb_rut.setText("Rut");

        lb_direcciion.setText("Direccion");

        lb_correo.setText("Correo");

        lb_telCel.setText("Tel");

        btn_contacto.setText("Contactar Proveedor");
        btn_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contactoActionPerformed(evt);
            }
        });

        btn_salir3.setText("Salir");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nombre)
                                    .addComponent(lb_codigo)
                                    .addComponent(lb_precio)
                                    .addComponent(lb_fecha)
                                    .addComponent(lb_nomProv)
                                    .addComponent(lb_rut)
                                    .addComponent(lb_direcciion)
                                    .addComponent(lb_correo)
                                    .addComponent(lb_telCel)))
                            .addComponent(btn_contacto))
                        .addContainerGap(392, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir3)
                        .addGap(54, 54, 54))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxt_buscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addGap(37, 37, 37)
                                .addComponent(btn_contacto))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_codigo)
                                .addGap(18, 18, 18)
                                .addComponent(lb_nombre)
                                .addGap(18, 18, 18)
                                .addComponent(lb_precio)
                                .addGap(18, 18, 18)
                                .addComponent(lb_fecha)
                                .addGap(18, 18, 18)
                                .addComponent(lb_nomProv)
                                .addGap(18, 18, 18)
                                .addComponent(lb_rut)
                                .addGap(18, 18, 18)
                                .addComponent(lb_direcciion)
                                .addGap(18, 18, 18)
                                .addComponent(lb_correo)
                                .addGap(18, 18, 18)
                                .addComponent(lb_telCel)
                                .addGap(62, 62, 62)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salir3)
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos", jInternalFrame3);

        jInternalFrame4.setVisible(true);

        jLabel13.setText("Buscar");

        jtxt_buscar3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxt_buscar3KeyTyped(evt);
            }
        });

        jtabla_productoRP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla_productoRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabla_productoRPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtabla_productoRP);

        jtabla_productosRecibidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabla_productosRecibidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtabla_productosRecibidosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jtabla_productosRecibidos);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel14.setText(">>");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");

        jButton3.setText("Eliminar Producto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_buscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel14))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jtxt_buscar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Recibir Pedido", jInternalFrame4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoSActionPerformed
        nuevoProducto();
    }//GEN-LAST:event_btn_nuevoSActionPerformed

    private void btn_modidicarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modidicarSActionPerformed
        if (this.idProdTS != null) {
            modificarProducto(this.idProdTS);
        } else {
            this.idProdTS = null;
        }
    }//GEN-LAST:event_btn_modidicarSActionPerformed

    private void btn_eliminarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarSActionPerformed
        if (this.idProdTS != null) {
            if (JOptionPane.showConfirmDialog(this, "Desea eliminar el producto: " + this.idProdTS) == 0) {
                eliminarProducto(idProdTS);

            } else {
                this.idProdTS = null;
            }
        }
    }//GEN-LAST:event_btn_eliminarSActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pedirActionPerformed
        pedir();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_pedirActionPerformed

    private void btn_modificarSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarSSActionPerformed
        if (this.idProdTSS != null) {
            modificarProducto(this.idProdTSS);
        } else {
            this.idProdTSS = null;
        }     // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificarSSActionPerformed

    private void btn_eliminarSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarSSActionPerformed
        if (this.idProdTSS != null) {
            if (JOptionPane.showConfirmDialog(this, "Desea eliminar el producto: " + this.idProdTSS) == 0) {
                eliminarProducto(idProdTSS);

            } else {
                this.idProdTSS = null;
            }
        }
    }//GEN-LAST:event_btn_eliminarSSActionPerformed

    private void btn_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contactoActionPerformed
        contactar();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_contactoActionPerformed

    private void jtablaProdSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaProdSMouseClicked
        int rowAtPoint = jtablaProdS.rowAtPoint(evt.getPoint()); // TODO add your handling code here:
        this.idProdTS = (Long) jtablaProdS.getValueAt(rowAtPoint, 0);        // TODO add your handling code here:
    }//GEN-LAST:event_jtablaProdSMouseClicked

    private void jtablaProdSSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaProdSSMouseClicked
        int rowAtPoint = jtablaProdSS.rowAtPoint(evt.getPoint()); // TODO add your handling code here:
        this.idProdTSS = (Long) jtablaProdSS.getValueAt(rowAtPoint, 0);         // TODO add your handling code here:
    }//GEN-LAST:event_jtablaProdSSMouseClicked

    private void jtablaProdPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablaProdPMouseClicked
        int rowAtPoint = jtablaProdP.rowAtPoint(evt.getPoint()); // TODO add your handling code here:
        this.idProdTP = (Long) jtablaProdP.getValueAt(rowAtPoint, 0);
        cargarDatosProducto();// TODO add your handling code here:
    }//GEN-LAST:event_jtablaProdPMouseClicked

    private void jtxt_buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_buscarKeyTyped
        util.filtrarTabla(jtxt_buscar.getText(), jtablaProdS);        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_buscarKeyTyped

    private void jtxt_buscar1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_buscar1KeyTyped
        util.filtrarTabla(jtxt_buscar1.getText(), jtablaProdSS);        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_buscar1KeyTyped

    private void jtxt_buscar2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_buscar2KeyTyped
        util.filtrarTabla(jtxt_buscar2.getText(), jtablaProdP);          // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_buscar2KeyTyped

    private void jtabla_productoRPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabla_productoRPMouseClicked
        int rowAtPoint = jtabla_productoRP.rowAtPoint(evt.getPoint());
        seleccionarProducto((Long) jtabla_productoRP.getValueAt(rowAtPoint, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_jtabla_productoRPMouseClicked

    private void jtabla_productosRecibidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabla_productosRecibidosMouseClicked
        int row = jtabla_productoRP.rowAtPoint(evt.getPoint());
        this.idproductoRecibido = (Long) jtabla_productoRP.getValueAt(row, 0);
    }//GEN-LAST:event_jtabla_productosRecibidosMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (this.idproductoRecibido != null) {
            if (JOptionPane.showConfirmDialog(this, "Desea eliminar el producto: " + this.idproductoRecibido.toString() + " de la lista de productos recibidos?") == 0) {
                int indice = getPosicionProdLista(this.idproductoRecibido);
                eliminarFila(indice);
            } else {
                this.idproductoRecibido = null;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxt_buscar3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_buscar3KeyTyped
        util.filtrarTabla(jtxt_buscar3.getText(), jtabla_productoRP);       // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_buscar3KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setearNuevoStock();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void cargarTablas() {
        cargarTablaEnStock();
        cargarTablaSinStock();
        cargarTablaProdC();
        reiniciarTablaProdRecibidos();
        cargarTablaProdRP();

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_contacto;
    private javax.swing.JButton btn_eliminarS;
    private javax.swing.JButton btn_eliminarSS;
    private javax.swing.JButton btn_modidicarS;
    private javax.swing.JButton btn_modificarSS;
    private javax.swing.JButton btn_nuevoS;
    private javax.swing.JButton btn_pedir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_salir2;
    private javax.swing.JButton btn_salir3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtablaProdP;
    private javax.swing.JTable jtablaProdS;
    private javax.swing.JTable jtablaProdSS;
    private javax.swing.JTable jtabla_productoRP;
    private javax.swing.JTable jtabla_productosRecibidos;
    private javax.swing.JTextField jtxt_buscar;
    private javax.swing.JTextField jtxt_buscar1;
    private javax.swing.JTextField jtxt_buscar2;
    private javax.swing.JTextField jtxt_buscar3;
    private javax.swing.JLabel lb_codigo;
    private javax.swing.JLabel lb_correo;
    private javax.swing.JLabel lb_direcciion;
    private javax.swing.JLabel lb_fecha;
    private javax.swing.JLabel lb_nomProv;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JLabel lb_precio;
    private javax.swing.JLabel lb_rut;
    private javax.swing.JLabel lb_telCel;
    // End of variables declaration//GEN-END:variables

    private void nuevoProducto() {
        if (JOptionPane.showConfirmDialog(this, "Desea agregar un nuevo Producto?") == 0) {
            AltaProducto altProd = new AltaProducto(this.escritorio);
            this.escritorio.add(altProd);
            altProd.setVisible(true);
        }
    }

    private void modificarProducto(long id) {
        if (JOptionPane.showConfirmDialog(this, "Desea modificar el producto: " + id) == 0) {
            ModificarProducto modProd = new ModificarProducto(this.escritorio, id);
            this.escritorio.add(modProd);
            modProd.setVisible(true);
        }
    }

    private void eliminarProducto(long id) {

        if (iCV.EliminarProducto(id)) {
            JOptionPane.showMessageDialog(this, "Se elimino el producto: " + id);
            cargarTablas();
        }

    }

    private void pedir() {
        if (JOptionPane.showConfirmDialog(this, "Desea realizar un pedido?") == 0) {
            JIF_pedidos pedidos = new JIF_pedidos(this.escritorio);
            this.escritorio.add(pedidos);
            pedidos.setVisible(true);

        }
    }

    private void contactar() {
        if (this.correoProv != null) {
            JIF_enviarCorreo enviarCorreo = new JIF_enviarCorreo(null, correoProv);
            //   enviarCorreo.recibeCorreo(this.correoProv);
            this.escritorio.add(enviarCorreo);
            enviarCorreo.setVisible(true);
        }

    }

    private void cargarTablaEnStock() {
        List<producto> productos = (List<producto>) iCV.getProductosDisponibles();
        if (productos.size() > 0) {
            String[] cabeceras = util.cabeceras(productos.get(0));
            DefaultTableModel nuevoModel = new DefaultTableModel(cabeceras, 0);
            for (producto p : productos) {
                Object[] data = {p.getCodigo(), p.getNombre(), p.getPrecio(), p.getDescripcion(), p.getCantidad(), p.getFechaDeCompra().toString(), p.getEstado()};
                nuevoModel.addRow(data);
            }
            jtablaProdS.setModel(nuevoModel);
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos en Stock!");
            jtablaProdS.setEnabled(false);
        }
    }

    private void cargarTablaSinStock() {
        List<producto> productos = (List<producto>) iCV.getProductosAgotados();
        if (productos.size() > 0) {
            String[] cabeceras = util.cabeceras(productos.get(0));
            DefaultTableModel nuevoModel = new DefaultTableModel(cabeceras, 0);
            for (producto p : productos) {
                Object[] data = {p.getCodigo(), p.getNombre(), p.getPrecio(), p.getDescripcion(), p.getCantidad(), p.getFechaDeCompra().toString(), p.getEstado()};
                nuevoModel.addRow(data);
            }
            jtablaProdSS.setModel(nuevoModel);
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos con Stock cero!");
            jtablaProdSS.setEnabled(false);
        }
    }

    private void cargarTablaProdC() {
        List<producto> productos = (List<producto>) iCV.getProductosTotales();
        if (productos.size() > 0) {
            String[] cabeceras = {"Id", "Nombre"};
            DefaultTableModel nuevoModel = new DefaultTableModel(cabeceras, 0);
            for (producto p : productos) {
                Object[] data = {p.getCodigo(), p.getNombre()};
                nuevoModel.addRow(data);
            }
            jtablaProdP.setModel(nuevoModel);
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos!");
            jtablaProdP.setEnabled(false);
        }
    }

    private void cargarTablaProdRP() {
        List<producto> productos = (List<producto>) iCV.getProductosTotales();
        if (productos.size() > 0) {
            String[] cabeceras = {"Id", "Nombre"};
            DefaultTableModel nuevoModel = new DefaultTableModel(cabeceras, 0);
            for (producto p : productos) {
                Object[] data = {p.getCodigo(), p.getNombre()};
                nuevoModel.addRow(data);
            }
            jtabla_productoRP.setModel(nuevoModel);
        } else {
            JOptionPane.showMessageDialog(this, "No hay productos!");
            jtabla_productoRP.setEnabled(false);
        }
    }

    private void reiniciarTablaProdRecibidos() {
        String[] cabeceras = {"Id Producto", "Nombre", "cantidad"};
        DefaultTableModel modeloN = new DefaultTableModel(cabeceras, 0);
        jtabla_productoRP.setModel(modeloN);
    }
    

    private void cargarDatosProducto() {
        if (this.idProdTP != 0) {
            this.prod = (producto) iCV.getProducto(this.idProdTP);
            lb_codigo.setText(String.valueOf(idProdTP));
            lb_nombre.setText(this.prod.getNombre());
            lb_precio.setText(String.valueOf(this.prod.getPrecio()));
            lb_fecha.setText(util.fechaString(this.prod.getFechaDeCompra(), 0));
            this.prov = this.prod.getProveedor();
            lb_correo.setText(this.prov.getCorreo());
            this.correoProv = this.prov.getCorreo();
            lb_nomProv.setText(this.prov.getNombreProveedor());
            lb_rut.setText(this.prov.getRUT());
            lb_direcciion.setText(this.prov.getDireccion());
            lb_telCel.setText(this.prov.getNumeroTelCel());
        }
    }

    private void seleccionarProducto(Long aLong) {
        producto p = iCV.getProducto(aLong);
        if (p != null) {
            DefaultTableModel modeloSet = (DefaultTableModel) jtabla_productosRecibidos.getModel();
            Object[] data = {p.getCodigo(), p.getNombre()};
            modeloSet.addRow(data);

        }
    }

    private int getPosicionProdLista(long id) {
        DefaultTableModel modeloSet = (DefaultTableModel) jtabla_productosRecibidos.getModel();
        Vector dataVector = modeloSet.getDataVector();
        for (int i = 0; i < dataVector.size(); i++) {
            Vector elementoVector = (Vector) dataVector.elementAt(i);
            if (estaEnEstaPosicion(elementoVector, id)) {
                return i;
            }

        }
        return 0;
    }

    private void eliminarFila(int indice) {
        DefaultTableModel modeloMod = (DefaultTableModel) jtabla_productosRecibidos.getModel();
        modeloMod.removeRow(indice);

    }

    private boolean estaEnEstaPosicion(Vector elementoVector, long id) {
        return ((Long) elementoVector.elementAt(0)).equals(id);
    }

    private boolean validarCantidades() {
        DefaultTableModel modelo = (DefaultTableModel) jtabla_productoRP.getModel();
        Vector datosVector = modelo.getDataVector();
        for (Object v : datosVector) {
            int cant = (Integer) ((Vector) v).elementAt(3);
            Long idP = (Long) ((Vector) v).elementAt(0);
            if (cant <= 0) {
                JOptionPane.showMessageDialog(this, "Las cantidades de los productos no pueden ser cero, revise!");
                jtabla_productoRP.requestFocus();
                return false;
            }
        }
        return true;
    }

    private HashMap armarDiccionarioConCantidades() {
        HashMap<Long, Integer> cantidadNuevaProd = new HashMap<>();
        DefaultTableModel modelo = (DefaultTableModel) jtabla_productosRecibidos.getModel();
        Vector dataVector = modelo.getDataVector();
        for (Object v : dataVector) {
            long idProd = (Long) ((Vector) v).elementAt(0);
            int cantidad = (Integer) ((Vector) v).elementAt(2);
            cantidadNuevaProd.put(idProd, cantidad);
        }
        return cantidadNuevaProd;
    }

    private void setearNuevoStock() {
        if (JOptionPane.showConfirmDialog(this, "Desea agregar las nuevas cantidades al stock actual?") == 0) {
            if (validarCantidades()) {
                HashMap<Long, Integer> cantidadesN = armarDiccionarioConCantidades();
                if (iCV.setearNuevaCantidadAlStockActual(cantidadesN)) {
                    JOptionPane.showMessageDialog(this, "Se actualizo el Stock actual de productos!");
                    limpiarRecibidos();

                } else {
                    JOptionPane.showMessageDialog(this, "Ocurrio un error al tratar de modificar el Stock!");
                }
            }

        }
    }

    private void limpiarRecibidos() {
        cargarTablas();
        this.idproductoRecibido = null;

    }
}
